ARG ALPINE_VERSION=3.22
FROM alpine:${ALPINE_VERSION}
RUN set -ex; \
apk update && apk add --no-cache tzdata iproute2 p7zip

#Tun2Socks
RUN mkdir /opt/tun2socks/
COPY ./tun2socks/tun2socks-linux-armv7.7z /opt/tun2socks/tun2socks.7z

#Xray core
RUN mkdir /opt/xray/
RUN mkdir /opt/xray/config/
COPY ./xray-core/Xray-linux-arm32-v7a.7z /opt/xray/xray.7z

COPY ./start.sh /opt/start.sh
RUN chmod +x /opt/start.sh
RUN sed -i 's/\r//' /opt/start.sh

RUN sed -i 's/^tty/#tty/' /etc/inittab
ENTRYPOINT ["/opt/start.sh"]
CMD []

#https://github.com/XTLS/Xray-core
#https://github.com/xjasonlyu/tun2socks